#!/usr/bin/perl

#[ Script ]--------------------------------------------------------------------#
#                                                                              #
# genericseek                                                                  #
#                                                                              #
# PT-br:                                                                       #
# Conta quantidade de ocorrências de um trecho até o final do log e armazena a #
# posição para contar a partir de onde parou.                                  #
# Ótimo  para  criar  monitorações  em  tempo  real  de  logs  que estão sendo #
# incrementados.                                                               #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Counts  number  of occurrences of a stretch to the end of the log and stores #
# the position to tell from where it stopped.                                  #
# Great  for  creating  monitoring  processes in real time logs that are being #
# increased.                                                                   #
#                                                                              #
# rlima@gmail.com                                                              #
# $Id: genericseek,v 1 2015/01/09 rlima Exp rlima $                            #
#                                                                              #
#[ License ]-------------------------------------------------------------------#
#                                                                              #
# Copyright (c) 2014 Reinaldo Marques de Lima reimlima@gmail.com               #
#                                                                              #
# PT-br:                                                                       #
# A permissão  é  concedida,  a título gratuito, a qualquer pessoa que obtenha #
# uma   cópia   deste   software   e   arquivos   de  documentação  associados #
# (o "Software"),  para  lidar  com  o  Software sem restrição, incluindo, sem #
# limitação,  os  direitos  de  usar,  copiar,  modificar,  mesclar, publicar, #
# distribuir,  sublicenciar,  e / ou vender cópias do Software, e permitir que #
# as  pessoas  a  quem  o  Software  é fornecido o façam, sujeito às seguintes #
# condições:                                                                   #
#                                                                              #
# O  aviso de copyright acima e este aviso de permissão devem ser incluídos em #
# todas as cópias ou partes substanciais do Software.                          #
#                                                                              #
# O  SOFTWARE É FORNECIDO "COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA #
# OU  IMPLÍCITA,  INCLUINDO,  SEM  LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, #
# ADEQUAÇÃO  A  UM  DETERMINADO  FIM E NÃO VIOLAÇÃO. EM NENHUM CASO OS AUTORES #
# OU  DIREITOS AUTORAIS TITULARES  SERÃo RESPONSÁVEIS POR QUALQUER RECLAMAÇÃO, #
# DANOS  OU  OUTRAS  RESPONSABILIDADES,  SEJA  EM  UMA  AÇÃO DE CUMPRIMENTO DE #
# CONTRATO OU DE OUTRA FORMA, DECORRENTE DE, OU EM CONEXÃO COM O SOFTWARE OU O #
# USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                           #
#                                                                              #
# Exceto  conforme  contido no presente aviso, o nome do (s) dos detentores de #
# direitos  autorais acima não devem ser utilizados em publicidade ou de outra #
# forma  para  promover  a venda, uso ou outras negociações deste Software sem #
# autorização prévia por escrito.                                              #
#                                                                              #
#----------------------------                                                  #
#                                                                              #
# EN:                                                                          #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of  this  software  and  associated  documentation  files  (the "Software"), #
# to  deal  in  the Software without restriction, including without limitation #
# the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense, #
# and/or  sell  copies  of  the  Software,  and  to permit persons to whom the #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The  above  copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED,  INCLUDING  BUT  NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, #
# FITNESS  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
# AUTHORS  OR  COPYRIGHT  HOLDERS  BE  LIABLE  FOR ANY CLAIM, DAMAGES OR OTHER #
# LIABILITY,   WHETHER   IN   AN   ACTION  OF  CONTRACT,  TORT  OR  OTHERWISE, #
# ARISING FROM,  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER #
# DEALINGS IN THE SOFTWARE.                                                    #
#                                                                              #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright #
# holders  shall  not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written authorization.  #
#                                                                              #
#------------------------------------------------------------------------------#

#[ Modulos ]-------------------------------------------------------------------#

use strict;
use JSON;
use XML::Simple;
use Config::Simple;

#[ Variaveis ]-----------------------------------------------------------------#

my $ds;
my %ds;
my $key;
my $log;
my $seek;
my $value;
my $config;
my $seekdb;
my $output;
my %keycount;
my $currsize;
my $newseekdb;
my $xmloutput;
my $jsonoutput;
my $occurrence;
my $outputformat;
my $timestamp = time();
my $configfile = 'genericseek.conf';

$keycount{count} = '0';

#[ Read config file ]----------------------------------------------------------#
$config = new Config::Simple($configfile);
$key = $config->param("key");
$log = $config->param("log");
$seekdb = $config->param("dbfile");
$occurrence = $config->param("occurrence");
$outputformat = $config->param("outputformat");

#[ XML Output Function ]-------------------------------------------------------#

sub xmlGenerate {
	$timestamp = shift;
	$key = shift;
	$value = shift;
	$xmloutput = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
	$ds = {filematch => [{timestamp => [$timestamp], key => [$key], value => [$value]}]};
	$xmloutput .= XMLout($ds, Rootname => "");
	return $xmloutput;
}

#[ JSON Output Function ]------------------------------------------------------#

sub jsonGenerate {	
	$timestamp = shift;
	$key = shift;
	$value = shift;
	%ds = ('filematch' => [{'timestamp' => $timestamp}, {'key' => $key}, {'value' => $value}]);
	$jsonoutput = encode_json \%ds;
	return $jsonoutput;
}

#[ Main Script ]---------------------------------------------------------------#

open(SEEK, $seekdb) or die("Error trying to open the file $seekdb\n");
$seek = <SEEK>;
close(SEEK);

open(LOG, $log) or die("Error trying to open the file $log\n");
$currsize = (stat($log))[7];

if ($seek =~ /$log=(\d+)\|(\d+);/){
	if ($currsize < $2){
		seek(LOG, 0, 0);
	}else{
		seek(LOG, $1, 0);
	}
}else{
	seek(LOG, 0, 0);
}

while(<LOG>){
	chomp($_);
	if($_ =~ /$occurrence/){
		$keycount{count}++;
	}
}

$value = $keycount{count};
$newseekdb .= $log ."=" . tell(LOG) ."|" . $currsize .";";

open(SEEK,"> $seekdb") or die("Error trying to open the file $seekdb\n");
print SEEK "$newseekdb";
close(SEEK);
close(LOG);

#[ Verify the chosen output formar, call the function and print ]--------------#

if ($outputformat =~ "xml") {
	$output .= xmlGenerate($timestamp, $key, $value);
} elsif ($outputformat =~ "json") {
	$output .= jsonGenerate($timestamp, $key, $value);
} else {
	$output .= "$key: $value\n";
}

print "$output";